language: node_js
node_js:
- "stable"
install: npm install
services:
  - postgresql
before_script:
  - psql -c 'create database propertypro_test;' -U postgres
scritp: npm test
after_success: npm run coveralls